development:
  adapter: postgresql
  encoding: unicode
  database: timelog_development
  host: localhost
  pool: 5
  username: postgres
  password: Test.?

test:
  adapter: postgresql
  encoding: unicode
  database: timelog_test
  host: localhost
  pool: 5
  username: postgres
  password: Test.?
