default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Test.?

development:
  <<: *default
  database: timelog_development
  host: localhost

test:
  <<: *default
  database: timelog_test
  host: localhost

production:
  <<: *default
  database: timelog_production